import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

export const productListScreenStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: theme.colors.backgroundSecondary,
		paddingHorizontal: theme.spacing.padding.md,
		paddingTop: theme.spacing.padding.md,
	},
	header: {
		backgroundColor: theme.colors.background,
		borderRadius: theme.spacing.borderRadius.lg,
		borderWidth: 1,
		borderColor: theme.colors.borderLight,
		paddingVertical: theme.spacing.lg,
		paddingHorizontal: theme.spacing.lg,
		marginBottom: theme.spacing.md,
		shadowColor: theme.colors.black,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.05,
		shadowRadius: 4,
		elevation: 2,
	},
	headerTitle: {
		color: theme.colors.text,
		fontSize: theme.typography.fontSize.xl,
		fontWeight: theme.typography.fontWeight.bold,
		marginBottom: theme.spacing.xs,
		letterSpacing: 0.2,
	},
	resultCount: {
		color: theme.colors.textSecondary,
		fontSize: theme.typography.fontSize.base,
		fontWeight: theme.typography.fontWeight.medium,
	},
	searchContainer: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: theme.colors.background,
		borderWidth: 1,
		borderColor: theme.colors.border,
		borderRadius: theme.spacing.borderRadius.md,
		paddingHorizontal: theme.spacing.md,
		marginBottom: theme.spacing.md,
		minHeight: 48,
	},
	searchInput: {
		flex: 1,
		color: theme.colors.text,
		fontSize: theme.typography.fontSize.base,
		paddingVertical: theme.spacing.sm,
	},
	clearButton: {
		width: 24,
		height: 24,
		borderRadius: theme.spacing.borderRadius.full,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: theme.colors.secondary,
		marginLeft: theme.spacing.sm,
	},
	clearButtonText: {
		color: theme.colors.textSecondary,
		fontSize: theme.typography.fontSize.base,
		fontWeight: theme.typography.fontWeight.bold,
		lineHeight: theme.typography.fontSize.base,
	},
	list: {
		paddingBottom: theme.spacing['6xl'] + theme.spacing.xl,
		gap: theme.spacing.sm,
	},
	emptyList: {
		flexGrow: 1,
		justifyContent: 'center',
		paddingBottom: theme.spacing['6xl'] + theme.spacing.xl,
	},
	productCard: {
		backgroundColor: theme.colors.background,
		borderWidth: 1,
		borderColor: theme.colors.borderLight,
		borderRadius: theme.spacing.borderRadius.lg,
		padding: theme.spacing.lg,
		shadowColor: theme.colors.black,
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.06,
		shadowRadius: 3,
		elevation: 2,
	},
	cardHeader: {
		marginBottom: theme.spacing.xs,
	},
	productId: {
		color: theme.colors.textLight,
		fontSize: theme.typography.fontSize.sm,
		fontWeight: theme.typography.fontWeight.medium,
	},
	productName: {
		color: theme.colors.text,
		fontSize: theme.typography.fontSize.md,
		fontWeight: theme.typography.fontWeight.bold,
		marginBottom: theme.spacing.xs,
	},
	productDescription: {
		color: theme.colors.textSecondary,
		fontSize: theme.typography.fontSize.base,
		lineHeight: theme.typography.fontSize.base * theme.typography.lineHeight.normal,
	},
	cardFooter: {
		marginTop: theme.spacing.sm,
		paddingTop: theme.spacing.sm,
		borderTopWidth: 1,
		borderTopColor: theme.colors.borderLight,
	},
	dateText: {
		color: theme.colors.textLight,
		fontSize: theme.typography.fontSize.sm,
		fontWeight: theme.typography.fontWeight.regular,
	},
	emptyState: {
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: theme.spacing['2xl'],
	},
	emptyStateText: {
		color: theme.colors.textSecondary,
		fontSize: theme.typography.fontSize.md,
		fontWeight: theme.typography.fontWeight.medium,
		textAlign: 'center',
	},
	errorState: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: theme.spacing['2xl'],
	},
	errorText: {
		color: theme.colors.danger,
		fontSize: theme.typography.fontSize.base,
		textAlign: 'center',
		marginBottom: theme.spacing.md,
		fontWeight: theme.typography.fontWeight.medium,
	},
	retryButton: {
		backgroundColor: theme.colors.primary,
		borderRadius: theme.spacing.borderRadius.sm,
		paddingVertical: theme.spacing.sm,
		paddingHorizontal: theme.spacing.lg,
	},
	retryButtonText: {
		color: theme.colors.text,
		fontSize: theme.typography.fontSize.base,
		fontWeight: theme.typography.fontWeight.bold,
		letterSpacing: 0.2,
	},
	loadingContainer: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: theme.colors.backgroundSecondary,
		paddingHorizontal: theme.spacing['2xl'],
	},
	loadingText: {
		marginTop: theme.spacing.md,
		color: theme.colors.textSecondary,
		fontSize: theme.typography.fontSize.base,
		fontWeight: theme.typography.fontWeight.medium,
	},
	fab: {
		position: 'absolute',
		right: theme.spacing.lg,
		bottom: theme.spacing.lg,
		width: 56,
		height: 56,
		borderRadius: 28,
		backgroundColor: theme.colors.primary,
		alignItems: 'center',
		justifyContent: 'center',
		shadowColor: theme.colors.black,
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.2,
		shadowRadius: 8,
		elevation: 5,
	},
	fabText: {
		color: theme.colors.text,
		fontSize: theme.typography.fontSize['2xl'],
		fontWeight: theme.typography.fontWeight.bold,
		lineHeight: theme.typography.fontSize['2xl'],
	},
});

export const searchInputPlaceholderColor = theme.colors.textLight;
