import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

export const productListScreenStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: theme.colors.backgroundSecondary,
		paddingHorizontal: theme.spacing.padding.md,
		paddingTop: theme.spacing.padding.md,
	},
	brandHeader: {
		backgroundColor: theme.colors.background,
		borderRadius: theme.spacing.borderRadius.md,
		borderWidth: 1,
		borderColor: theme.colors.borderLight,
		paddingVertical: theme.spacing.md,
		paddingHorizontal: theme.spacing.md,
		alignItems: 'center',
		marginBottom: theme.spacing.md,
	},
	brandTitle: {
		color: theme.colors.text,
		fontSize: theme.typography.fontSize.base,
		fontWeight: theme.typography.fontWeight.bold,
		letterSpacing: 0.8,
	},
	searchSection: {
		marginBottom: theme.spacing.sm,
	},
	searchContainer: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: theme.colors.background,
		borderWidth: 1,
		borderColor: theme.colors.border,
		borderRadius: theme.spacing.borderRadius.md,
		paddingHorizontal: theme.spacing.md,
		marginBottom: theme.spacing.md,
		minHeight: 44,
	},
	searchInput: {
		flex: 1,
		color: theme.colors.text,
		fontSize: theme.typography.fontSize.sm,
		paddingVertical: theme.spacing.sm,
	},
	clearButton: {
		paddingHorizontal: theme.spacing.xs,
		paddingVertical: theme.spacing.xs,
		alignItems: 'center',
		justifyContent: 'center',
		marginLeft: theme.spacing.sm,
	},
	clearButtonText: {
		color: theme.colors.textSecondary,
		fontSize: theme.typography.fontSize.sm,
		fontWeight: theme.typography.fontWeight.medium,
	},
	list: {
		paddingBottom: theme.spacing['6xl'] + theme.spacing.xl,
		gap: 0,
	},
	emptyList: {
		flexGrow: 1,
		justifyContent: 'center',
		paddingBottom: theme.spacing['6xl'] + theme.spacing.xl,
	},
	productCard: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		backgroundColor: theme.colors.background,
		borderWidth: 1,
		borderColor: theme.colors.borderLight,
		borderRadius: theme.spacing.borderRadius.md,
		paddingVertical: theme.spacing.md,
		paddingHorizontal: theme.spacing.md,
		marginBottom: theme.spacing.sm,
	},
	productInfo: {
		flex: 1,
		paddingRight: theme.spacing.md,
	},
	productId: {
		color: theme.colors.textLight,
		fontSize: theme.typography.fontSize.sm,
		fontWeight: theme.typography.fontWeight.regular,
	},
	productName: {
		color: theme.colors.text,
		fontSize: theme.typography.fontSize.base,
		fontWeight: theme.typography.fontWeight.bold,
		marginBottom: theme.spacing.xs,
	},
	productChevron: {
		color: theme.colors.textLight,
		fontSize: theme.typography.fontSize.xl,
		fontWeight: theme.typography.fontWeight.bold,
	},
	emptyState: {
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: theme.spacing['2xl'],
	},
	emptyStateText: {
		color: theme.colors.textSecondary,
		fontSize: theme.typography.fontSize.md,
		fontWeight: theme.typography.fontWeight.medium,
		textAlign: 'center',
	},
	errorState: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: theme.spacing['2xl'],
	},
	errorText: {
		color: theme.colors.danger,
		fontSize: theme.typography.fontSize.base,
		textAlign: 'center',
		marginBottom: theme.spacing.md,
		fontWeight: theme.typography.fontWeight.medium,
	},
	retryButton: {
		backgroundColor: theme.colors.primary,
		borderRadius: theme.spacing.borderRadius.sm,
		paddingVertical: theme.spacing.sm,
		paddingHorizontal: theme.spacing.lg,
	},
	retryButtonText: {
		color: theme.colors.text,
		fontSize: theme.typography.fontSize.base,
		fontWeight: theme.typography.fontWeight.bold,
		letterSpacing: 0.2,
	},
	loadingContainer: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: theme.colors.backgroundSecondary,
		paddingHorizontal: theme.spacing['2xl'],
	},
	loadingText: {
		marginTop: theme.spacing.md,
		color: theme.colors.textSecondary,
		fontSize: theme.typography.fontSize.base,
		fontWeight: theme.typography.fontWeight.medium,
	},
	fab: {
		position: 'absolute',
		right: theme.spacing.lg,
		bottom: theme.spacing.lg,
		width: 56,
		height: 56,
		borderRadius: 28,
		backgroundColor: theme.colors.primary,
		alignItems: 'center',
		justifyContent: 'center',
		shadowColor: theme.colors.black,
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.2,
		shadowRadius: 8,
		elevation: 5,
	},
	fabText: {
		color: theme.colors.text,
		fontSize: theme.typography.fontSize['2xl'],
		fontWeight: theme.typography.fontWeight.bold,
		lineHeight: theme.typography.fontSize['2xl'],
	},
});

export const searchInputPlaceholderColor = theme.colors.textLight;
